### PR TITLE
Update dependencies.

### PR DESCRIPTION
**Pull request by jheer**
Changes:
- Bump dev dependencies.
- Update duckdb-wasm.
- Update to arrow 13, matching duckdb-wasm.

Notes:
- **Do not update duckdb to 9.1**, due to unresolved bugs (e.g., duckdb/duckdb#8944)

### CODE REVIEW

**Comment by domoritz** [comment]
The python tests should work again after #219

**Comment by jheer** [comment]
Hmm, @domoritz looks like the Python DuckDB build is still failing after merging #219 and #220?

**Comment by domoritz** [comment]
It's passing in main (https://github.com/uwdata/mosaic/actions/runs/7008521851/job/19064999539) but looks like the update isn't happy.

**Comment by domoritz** [comment]
I rebased the commit so you get the updates now. Tests pass ✅ .

**Review by domoritz — APPROVED** [review]

**Pull request merged**
