### PR TITLE
feat: rust server

### PR DESCRIPTION
**Pull request by domoritz**
* DuckDB server written in Rust.
  * Supports http/1, http/2, and websockets.
  * Caching and bundling support.
* Fixes bundle logic in demo page.
* Rewrite priority queue as a class.
* Uses DuckDB-rs 1.0 which was released recently.

After this is merged, my plan is to use the http/2 support for parallel queries from the browser.

### CODE REVIEW

**Comment by domoritz** [comment]
I looked into using rust from python and it's pretty straight forward but probably doesn't make as much sense for the widget since it's so simple already and I don't know how we would allow duckdb to query pandas through rust.

**Review by jheer — APPROVED** [review]

**Comment by jheer** [comment]
Overall this looks good to me. However, I noticed that the Rust tests appear to take a very long time. It's took over 20 minutes, apparently due to lots of download and compilation steps. This does not make for a great developer experience here on GitHub. Any ideas for how to address this?

**Comment by domoritz** [comment]
It looks like we are compiling twice right now. I'll check what's up with that. I might also be able to add caching to reduce build times.

**Comment by domoritz** [comment]
Took some experimentation but got it down to 37s.

**Comment by mhkeller** [comment]
Thanks again for your work in implementing this!

**Comment by domoritz** [comment]
You're welcome. How are you using it?

**Comment by mhkeller** [comment]
I've been working on an app that queries postgres and, among other things, allows for custom mosaic visualizations off of the query result.

**Pull request merged**
